### ISSUE TITLE
Theme ignores "menu" override

### ISSUE THREAD

**Issue by Lukaszeq** [acezalba/canvas#3]
I have a folder with a menu string override enabled, but the theme still shows the title instead (in this case, just "About me").

<img width="931" alt="Grav override" src="https://github.com/user-attachments/assets/4644d0f7-6c1f-4015-8fb6-f0c9c2f19d3f">

**Comment by acezalba** [comment]
I've looked into it, and I saw that the "menu" override is a specific page header that has to be manually supported by the theme (a lot of page headers aren't automatically supported by themes btw). In my case, the reason why this override is being ignored is because I am directly calling `page.title` instead of `page.menu` from my navigation partial. I'll see to it that it is supported later. :)

**Comment by acezalba** [comment]
I've added support for `page.menu` in the [latest release](https://github.com/acezalba/grav-theme-canvas/releases/tag/v3.0.3). Let me know if it works for you @Lukaszeq.
